plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.garhwaltournadventure.booking'
    compileSdk 35

    defaultConfig {
        applicationId 'com.garhwaltournadventure.booking'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.3'
    }

    dependencies {
        implementation 'androidx.core:core:1.15.0'
        implementation platform('com.google.firebase:firebase-bom:34.19.0')
        implementation 'com.google.firebase:firebase-messaging'
    }

    buildTypes {
        debug {
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
        }
    }
}
